### ISSUE TITLE
Can u help me with this problem, if you can show me step by step I wil really appreciate it, thank you so much!!! And below is the debug info.

### ISSUE THREAD

**Issue by danhthai113** [jasonlws/anki-addon-mcnt#6]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.main", line 219, in on_window_init
  File "aqt.main", line 266, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 318, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "_aqt.hooks", line 4101, in __call__
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\1859136708\__init__.py", line 94, in create_update_note_type
    update_note_type(mw.col)
  File "C:\Users\LENOVO\AppData\Roaming\Anki2\addons21\1859136708\__init__.py", line 84, in update_note_type
    col.models.save(model)
  File "anki.models", line 573, in save
  File "anki.models", line 556, in update
  File "anki._backend_generated", line 1107, in add_or_update_notetype
  File "anki._backend", line 171, in _run_command
anki.errors.CardTypeError: Card template ⁨1⁩ in notetype '⁨Multiple Choice Note Type⁩' has a problem.<br>Field '⁨ref⁩' not found.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Multiple Choice Note Type ['1859136708', 2024-09-12T04:11, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T18:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1859136708

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by ArlindoMED** [comment]
You could link an editorial explanation field to each alternative, so that it is possible to include explanations about the alternatives during the review (directly on the back of the card). 
I tried to make this extension from scratch using AI, but I couldn't.
![Image](https://github.com/user-attachments/assets/764b57b9-d977-4eb2-8c0d-1c001d491706)

**Comment by ProsperousHeart** [comment]
I don't have issues ATM ... is this a new install? Have you shut down and then restart the app after installing the module?

I installed Anki yesterday and this module today
